title: JSON Schema Validation
description: "Demo : working with json schemas"
type: object
additionalProperties: True
properties:
  API_HASH:
    description: Añadir una description
    type: string
    pattern: "[A-z0-9]{32}"
  API_ID:
    description: Añadir una description
    type: integer
    minimum: 1
  CHAT_ID:
    description: Añadir una description
    type: integer 
required:
  - API_HASH
  - API_ID
  - CHAT_ID
